# Generated by Django 5.2 on 2025-04-25 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('picture', models.ImageField(default='auction.png', upload_to='auction_images')),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('1', 'Apparel and Accessories'), ('2', 'Consumer Electronics'), ('3', 'Home and Kitchen Appliances'), ('4', 'Health and Beauty'), ('5', 'Furniture and Decor'), ('6', 'Sports and Fitness'), ('7', 'Books and Media'), ('8', 'Toys and Games'), ('9', 'Food and Beverage'), ('10', 'Auto and Parts'), ('11', 'Other or Uncategorized')], default='11')),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deactive'), ('C', 'Closed')], default='A')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='watch_list',
            field=models.ManyToManyField(blank=True, to='auctions.auction'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_auction', to='auctions.auction')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'ordering': ('price',),
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='top_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_top_bid', to='auctions.bid'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=600)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('date',),
            },
        ),
    ]
