# Generated by Django 5.2 on 2025-04-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_userprofile_watch_list_bid_auction_top_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
