# Generated by Django 5.2 on 2025-04-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
