# Generated by Django 5.2 on 2025-04-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='last_updated',
        ),
    ]
