# Generated by Django 5.2 on 2025-05-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_bid_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
