# Generated by Django 5.2 on 2025-05-01 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_comment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('1', 'Apparel and Accessories'), ('2', 'Consumer Electronics'), ('3', 'Home and Kitchen Appliances'), ('4', 'Health and Beauty'), ('5', 'Furniture and Decor'), ('6', 'Sports and Fitness'), ('7', 'Books and Media'), ('8', 'Toys and Games'), ('9', 'Food and Beverage'), ('10', 'Auto and Parts'), ('11', 'Other or Uncategorized')], db_index=True, default='11'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Deactive'), ('C', 'Closed')], db_index=True, default='A'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status', 'category', 'price'], name='auctions_au_status_874074_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', 'bidder'], name='auctions_bi_auction_331710_idx'),
        ),
    ]
